# Generated by Django 5.2.3 on 2025-07-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='department',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='job_title',
            new_name='position',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='ifsc_code',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='joining_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
    ]
