# Generated by Django 5.2.3 on 2025-07-11 14:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_employee_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date payroll was created'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payroll',
            name='month',
            field=models.CharField(default='2025-07', help_text='Month for which the payroll is generated', max_length=7),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='net_salary',
            field=models.FloatField(help_text='Net salary after deductions'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='payslip_pdf',
            field=models.FileField(blank=True, help_text='Optional payslip file', null=True, upload_to='payslips/'),
        ),
    ]
