# Generated by Django 5.2.3 on 2026-02-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_payroll_created_at_alter_payroll_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='month',
            field=models.CharField(default='2026-02', help_text='Month for which the payroll is generated', max_length=7),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='net_salary',
            field=models.DecimalField(decimal_places=2, help_text='Net salary after deductions', max_digits=10),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='allowances',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='basic',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='hra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
