# Generated by Django 5.2.3 on 2026-02-21 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_payroll_month_alter_payroll_net_salary_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['full_name'], 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='payroll',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Payrolls'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='salarystructure',
            options={'verbose_name_plural': 'Salary Structures'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='month',
            field=models.CharField(default='2026-02', max_length=7),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='net_salary',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='payslip_pdf',
            field=models.FileField(blank=True, null=True, upload_to='payslips/'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='myapp.salarystructure'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('hr', 'HR'), ('emp', 'Employee')], default='emp', max_length=10),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='allowances',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='basic',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structures', to='myapp.employee'),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='hra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
