# Generated by Django 5.2.3 on 2026-03-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_employee_options_alter_payroll_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='month',
            field=models.CharField(default='2026-03', max_length=7),
        ),
    ]
